### ISSUE TITLE
UROPA_GUI web server not working

### ISSUE THREAD

**Issue by DimKat** [loosolab/UROPA#11]
Dear UROPA builders,

I am a frequent user of the UROPA GUI software that was hosted online on: http://loosolab.mpi-bn.mpg.de/UROPA_GUI/

I tried today to access the tool but I repeatedly get a 502 Bad Gateway error. 

Have you by any chance discontinued the support of the online server or are you moving the tool to a different directory? 

I have UROPA also installed in Miniconda but I find the online tool particularly convenient.

Looking forward to your response.

Kind regards,

Dimitris

**Comment by mlooso** [comment]
Dear Dimitris, please try again if you can reach the server now, best Mario
