### ISSUE TITLE
General question about UROPA

### ISSUE THREAD

**Issue by adelosan521** [loosolab/UROPA#18]
Hi,

I have a general question about UROPA. I am trying to conduct analysis of ATAC-seq data. What does running UROPA on the peaks files do? How does it make the results better than if I didn't use it?

Niko

**Comment by msbentsen** [comment]
Hi Niko, 

UROPA is a tool for assigning peak locations to nearby genomic features e.g. genes/exons/etc. If you have done ATAC-seq, the ATAC-seq peaks are mostly useless without knowing where they are located on the genome. So a classical ATAC-seq analysis might be to find differential peaks between two conditions, annotate these peaks, and collect the nearby genes to say something about the epigenetic regulation.

UROPA supports advanced annotation queries, meaning that you customize when a peak is assigned to a gene using for example: distance, orientation, feature attributes and strand. So depending on your application, you can customize UROPA to assign peaks -> genes.

Best Mette
