### ISSUE TITLE
Summary feature distance inconsistency

### ISSUE THREAD

**Issue by Hrovatin** [loosolab/UROPA#2]
I have noticed that when I set the distance to, for example 1300,1400, my summary both of allhits and besthits contains distance graph only up to 350 bp distance. I have checked resulting bed files and pairs with distance above 350 bp are definitel reported. 
Could you exmplain me what is happening.

**Comment by msbentsen** [comment]
Hi Hrovatin,
I discovered that we have previously set a "maximum distance" for these plots, meaning that your peak->feature hits were there in the results but were not shown in the plot. This probably only makes sense for very large distances, so I have removed this limit in UROPA 3.3.4 (on pypi but not in conda yet). Hope this helps you out!
