### ISSUE TITLE
Features on the (-) strand marked "Downstream" but are actually upstream

### ISSUE THREAD

**Issue by mcsimenc** [loosolab/UROPA#3]
Thanks for developing UROPA!

When I look at genes where the associated peak is marked "Downstream" in my UROPA output in a genome browser, I see that the peaks are upstream of the genes, which are on the - strand. Could this be a bug where strand is not taken into account? In the docs it says upstream/downstream is relative to strand, but my output does not reflect that.

Best,

Matt

**Comment by msbentsen** [comment]
Hi Matt,
You are completely right - this was a bug. There was an error in how the assignment of downstream/upstream was set in comparison to the feature anchor. We just released a fix in `uropa 3.5.3`, where the strand is taken into account. Sorry for the inconvenience! 
Best Mette

**Comment by mcsimenc** [comment]
Hi Mette, thank you for the speedy response! I'll upgrade my UROPA installation.
